% Step6_ReplayDecayFit.m
% =========================================================================
% Fits a power-law decay model to the replay similarity curve C(Delta_m)
% and produces a thesis-quality two-panel figure:
%   (a) Log-log plot of replay decay with power-law fits for each N
%   (b) Fitted exponent vs network size N with error bars
%
% INPUT:  Results/C(delta_m).mat  (generated by Step5_Statistics.m)
% OUTPUT: Results/ReplayDecay_PowerLaw.pdf / .png
% =========================================================================

clc; clear;

%% Resolve paths
scriptDir = fullfile(pwd, 'Analysis', 'Part5(NoisyConsolidation)');
if ~isfolder(fullfile(scriptDir, 'Results'))
    scriptDir = pwd;
end
fname = fullfile(scriptDir, 'Results', 'C(delta_m).mat');
if ~isfile(fname)
    error('Cannot find C(delta_m).mat. Run Step5_Statistics.m first.');
end
load(fname, 'allRecords');

%% Sort records by N
Nlist = arrayfun(@(r) r.N, allRecords);
[Nlist, sortIdx] = sort(Nlist);
allRecords = allRecords(sortIdx);
nRec = numel(allRecords);

%% Set up colors
colors = lines(nRec);

% Count simulations per N from the Data directory
nMems = 20; noise_strength = 100;
simCounts = zeros(nRec, 1);
for i = 1:nRec
    dataDir = fullfile(scriptDir, 'Data', ['N' num2str(allRecords(i).N)], ...
        ['nMems' num2str(nMems)], ['noise' num2str(noise_strength) '%']);
    if isfolder(dataDir)
        d = dir(dataDir);
        simCounts(i) = sum([d.isdir] & ~ismember({d.name}, {'.', '..'}));
    end
end

%% Panel (a): Log-log decay curves with power-law fits
fig = figure('Position', [100 100 1400 500], 'Color', 'w');

subplot(1, 2, 1); hold on;

exponents = zeros(nRec, 1);
errors    = zeros(nRec, 1);
legendEntries = {};

for i = 1:nRec
    rec = allRecords(i);
    x_all = rec.X;  % X is already Delta_m + 1 (1, 2, 3, ...)

    % Plot all points as connected dots
    valid_plot = rec.Y > 0;
    plot(x_all(valid_plot), rec.Y(valid_plot), 'o-', 'Color', colors(i,:), ...
        'MarkerSize', 5, 'LineWidth', 1.2, 'MarkerFaceColor', colors(i,:), ...
        'DisplayName', sprintf('N = %d', rec.N));

    % Fit power law: C ~ (Delta_m + 1)^b  in log-log space
    valid_fit = rec.Y > 0;
    x = x_all(valid_fit);
    y = rec.Y(valid_fit);

    % Trim tail (first 70% of points for robust fit)
    cutoff = round(0.7 * numel(x));
    xfit = x(1:cutoff);
    yfit_data = y(1:cutoff);

    % Linear fit in log-log space
    mdl = fitlm(log10(xfit), log10(yfit_data));
    exponents(i) = mdl.Coefficients.Estimate(2);
    errors(i)    = mdl.Coefficients.SE(2);

    % Overlay fit line (straight in log-log space)
    x_fitline = logspace(log10(min(x)), log10(max(x)), 100);
    y_fitline = 10.^(predict(mdl, log10(x_fitline)'));
    plot(x_fitline, y_fitline, '--', 'Color', colors(i,:), 'LineWidth', 1.5, ...
        'HandleVisibility', 'off');

    legendEntries{end+1} = sprintf('N = %d (n=%d, b = %.2f, R^2 = %.2f)', ...
        rec.N, simCounts(i), exponents(i), mdl.Rsquared.Ordinary);
end

set(gca, 'XScale', 'log', 'YScale', 'log');
xlabel('$\Delta m + 1$', 'Interpreter', 'latex');
ylabel('Mean Replay Similarity');
title('(a) Replay Decay vs Memory Distance');
legend(legendEntries, 'Location', 'southwest', 'Box', 'off');
grid on;

%% Panel (b): Exponent vs N with error bars
subplot(1, 2, 2); hold on;

errorbar(Nlist, exponents, errors, 'ko', 'LineWidth', 1.5, ...
    'MarkerFaceColor', [0.3 0.5 0.8], 'MarkerSize', 8, ...
    'DisplayName', 'Fitted exponent');
yline(-1, '--r', 'LineWidth', 1.5, 'DisplayName', '$b = -1$', ...
    'Interpreter', 'latex');

% Weighted mean
w = 1 ./ errors.^2;
b_mean = sum(exponents .* w) / sum(w);
b_err  = sqrt(1 / sum(w));
yline(b_mean, ':', 'Color', [0.2 0.6 0.2], 'LineWidth', 1.5, ...
    'DisplayName', sprintf('Weighted mean = %.2f', b_mean));

set(gca, 'XScale', 'log');
xlabel('Network Size $N$', 'Interpreter', 'latex');
ylabel('Power-Law Exponent $b$', 'Interpreter', 'latex');
title('(b) Exponent vs Network Size');
legend('Location', 'southeast', 'Box', 'off', ...
    'Interpreter', 'latex');
grid on;
ylim([min(exponents) - 0.15, max(exponents) + 0.15]);

%% Print summary
fprintf('\n--- Power-Law Fit Summary ---\n');
T = table(Nlist, exponents, errors, 'VariableNames', {'N', 'Exponent', 'SE'});
disp(T);
fprintf('Weighted mean exponent: b = %.4f +/- %.4f\n', b_mean, b_err);

chi2 = sum((exponents - (-1)).^2 ./ errors.^2);
dof  = nRec - 1;
p_chi2 = 1 - chi2cdf(chi2, dof);
fprintf('Chi-square test for b = -1: chi2/dof = %.2f/%d = %.2f, p = %.3f\n', ...
    chi2, dof, chi2/dof, p_chi2);

%% Export
outputDir = fullfile(scriptDir, 'Results');
if ~exist(outputDir, 'dir'), mkdir(outputDir); end
outPath = fullfile(outputDir, 'ReplayDecay_PowerLaw');
exportgraphics(fig, outPath + ".pdf", 'ContentType', 'vector');
exportgraphics(fig, outPath + ".png", 'ContentType', 'image', 'Resolution', 300);
fprintf('Figure exported to:\n  %s.pdf\n  %s.png\n', outPath, outPath);
