% Step6_C_Delta_m_fit.m
% =========================================================================
% Power-law analysis of the noisy-consolidation similarity decay C(Delta_m).
%
% Loads the per-network-size similarity curves produced by Step5_Statistics
% and tests whether the decay of Pearson correlation with memory offset
% Delta_m follows a power law:   C(Delta_m) ~ (Delta_m)^beta.
%
% SECTIONS:
%   1. Raw data plot      – log-log overlay of C(Delta_m) for every N.
%   2. Power-law fitting  – OLS in log-log space (first 70 % of points) to
%                           estimate the exponent beta and its SE for each N.
%   3. Exponent vs N      – error-bar plot of beta(N) with a reference at -1.
%   4. Weighted mean      – inverse-variance weighted average of beta.
%   5. Chi-square test    – goodness-of-fit test for H0: beta = -1.
%
% INPUT:
%   Results/C(delta_m).mat  –  struct array allRecords (fields: N, X, Y)
%                              generated by Step5_Statistics.m
% =========================================================================

clear; clc;

%% Resolve paths relative to the project root
% Try several possible working directories: pwd may be the project root,
% the script folder itself, or somewhere else entirely.
scriptDir = fullfile(pwd, 'Analysis', 'Part5(NoisyConsolidation)');
if ~isfolder(fullfile(scriptDir, 'Results'))
    scriptDir = pwd;
end
load(fullfile(scriptDir, 'Results', 'C(delta_m).mat'));

%% 1. Raw data: C(Delta_m) for each network size N
figure; hold on;
for i = 1:numel(allRecords)
    rec = allRecords(i);
    plot(rec.X, rec.Y, 'o-','DisplayName', sprintf('N=%d', rec.N));
end
hold off;
xlabel('$\Delta m$', 'Interpreter', 'latex');
ylabel('$C(\Delta m)$', 'Interpreter', 'latex');
legend('show', 'Location', 'best');
title('Similarity Decay $C(\Delta m)$ for Different Network Sizes', 'Interpreter', 'latex');
grid on;
set(gca, 'XScale', 'log', 'YScale', 'log');

%% 2. Power-law fit: C(Delta_m) ~ (Delta_m)^beta  (log-log OLS)
figure; hold on;
nRec = numel(allRecords);
exponents = zeros(nRec, 1);
errors = zeros(nRec, 1);
Nlist = zeros(nRec, 1);

for i = 1:nRec
    rec = allRecords(i);
    valid = rec.X > 0 & rec.Y > 0;
    x = rec.X(valid);
    y = rec.Y(valid);

    % Keep only the first 70 % of points (discard noisy tail)
    cutoff = round(0.7 * numel(x));
    x = x(1:cutoff);
    y = y(1:cutoff);

    % Linear fit in log-log space: log10(C) = beta * log10(Delta_m) + c
    p = polyfit(log10(x), log10(y), 1);
    yfit = 10.^(polyval(p, log10(x)));
    plot(x, y, 'o-');
    plot(x, yfit, '--', 'LineWidth', 1);

    exponents(i) = p(1);   % slope = power-law exponent beta
    Nlist(i) = rec.N;

    % Standard error of the slope via linear model
    mdl = fitlm(log10(x), log10(y));
    errors(i) = mdl.Coefficients.SE(2);
end

set(gca, 'XScale', 'log', 'YScale', 'log');
xlabel('$\Delta m$', 'Interpreter', 'latex');
ylabel('$C(\Delta m)$', 'Interpreter', 'latex');
legend(arrayfun(@(n) sprintf('N=%d', n), Nlist, 'UniformOutput', false), 'Location', 'best');
title('Power-Law Fit of $C(\Delta m)$', 'Interpreter', 'latex');

% Display fitted exponents
T = table(Nlist, exponents, errors, 'VariableNames', {'N', 'Exponent', 'SE'});
disp(T)

%% 3. Exponent vs network size N
figure; hold on;
errorbar(Nlist, exponents, errors, 'o', 'LineWidth', 2)
yline(-1, '--r', '$\beta = -1$', 'Interpreter', 'latex')
xlabel('Network Size $N$', 'Interpreter', 'latex');
ylabel('Exponent $\beta$', 'Interpreter', 'latex');
title('Power-Law Exponent vs Network Size', 'Interpreter', 'latex');
set(gca, 'XScale', 'log');
grid on;

%% 4. Weighted mean exponent (inverse-variance weighting)
w = 1 ./ errors.^2;
b_mean = sum(exponents .* w) / sum(w);
b_err = sqrt(1 / sum(w));
fprintf('Weighted mean exponent = %.4f +/- %.4f\n', b_mean, b_err)

%% 5. Chi-square test for H0: beta = -1
b0 = -1;
chi2 = sum((exponents - b0).^2 ./ errors.^2);
dof = numel(exponents) - 1;
fprintf('Chi-square/dof = %.2f/%d = %.2f\n', chi2, dof, chi2/dof)
